name: Slack notification
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CUSTOM_PAYLOAD: '{"text": "Website deploy finished: ${{ github.event.workflow_run.conclusion }}"}'
          SLACK_ICON: 'https://avatars.githubusercontent.com/u/186667446'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
